language: cpp
compiler:
  - gcc

before_script:
  - sudo apt-add-repository ppa:zoogie/sdl2-snapshots -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y libglew-dev libsdl2-dev
script: cd build/ && cmake ../CMakeLists.txt && make
